HTTP/1.0 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>error</title>
</head>
<body>
	<center>
		<h1>Service no available</h1><br>
		<h1>ERROR 503</h1>
		<img src="https://cdn-icons-png.flaticon.com/512/1886/1886495.png" width="40%"><br>
		<h2>Sorry for the inconvenience, try again later</h2>
	</center>
</body>
</html>